DATA SCIENCE SPECIALISM

MODULE 4 - Exploratory Data Analysis

PROJECT 1
==================================================================================

PLOT 1 DETAILS -

Graph style	:	histogram

Graph size	:	480 pixels by 480 pixels

Graph title :	Global Active Power

Dataset		:	dates 2007-02-01 and 2007-02-02 (1st & 2nd of February 2007)

y axis title:	Frequency
y axis scale: 	0 - 1200

x axis title:	Global Active Power (kilowatts)
x axis scale:	0 - 6

=================================================================================

R SCRIPT

##1 - saving the output graph (as a png) generated by the R script below - automatically saved as size 480 x 480 pixels
png("plot1.png")

	##2 - loading libraries
	library(data.table)

		##3 - reading the dataset into R
		household <- read.table("household_power_consumption.txt", header = TRUE, sep = c(";"), na.strings = "?")
	
			##4 - select coloumns contains date, time, global active power
				householdsubset <- household[c(1,3)]
	
				##5 - renaming the columns of the household dataset - tidy data set
				names(householdsubset) <- gsub("Date", "date", names(householdsubset))
				names(householdsubset) <- gsub("Global_active_power", "globalactivepower (kilowatts)", names(householdsubset))
	
					##6 - selecting the rows 1st/2nd February 2007. row numbers 66637-69516
					##changing date from factor to time
					householdsubset$date <- strptime(householdsubset$date, format = "%d/%m/%Y")	
					##select the rows 1st/2nd February 2007
					datasubset <- subset(householdsubset, date >= "2007-02-01" & date <= "2007-02-02")
	
						##7 - generating the graph
						hist(datasubset$globalactivepower, main = "Global Active Power", xlab = "Global Active Power (kilowatts)", col = "red")

							##8 - closing the graphic png file
							dev.off()
