DATA SCIENCE SPECIALISM

MODULE 4 - Exploratory Data Analysis

PROJECT 1
==================================================================================

PLOT 3 DETAILS -

Graph style	:	line graph with legend in top right corner

Graph size	:	480 pixels by 480 pixels

Graph title :	none

Dataset		:	dates 2007-02-01 and 2007-02-02 (1st & 2nd of February 2007)

y axis title:	Energy sub metering (Watt Hour)
y axis scale: 	0 - 30

x axis title:	none
x axis scale:	Thu, Fri, Sat

=================================================================================

R SCRIPT

##1 - saving the output graph (as a png) generated by the R script below - automatically saved as size 480 x 480 pixels
png("plot3.png")


	##2 - loading libraries
	library(data.table)

	
		##3 - reading the dataset into R
		household <- read.table("household_power_consumption.txt", header = TRUE, sep = c(";"), na.strings = "?")
	
	
			##4 - create two data tables - 1) date & time, 2) global active power
			householddatesubset <- household[c(1:2)]
			meteringsubset <- household[c(7:9)]
				
				##5 - creating a data frame with merged date and time columns
				
				##5.1 - merged date and time into one column
				mergedsubset <- paste(householddatesubset$Date, householddatesubset$Time, sep = " ")

				##5.2 - merge date/time df with power df
				householdsubset <- cbind(mergedsubset, meteringsubset)

				
					##6 - renaming the columns of the household dataset - tidy data set
					names(householdsubset) <- gsub("mergedsubset", "date", names(householdsubset))
					
					names(householdsubset) <- gsub("Sub_metering_1", "submetering1", names(householdsubset))
					
					names(householdsubset) <- gsub("Sub_metering_2", "submetering2", names(householdsubset))
					
					names(householdsubset) <- gsub("Sub_metering_3", "submetering3", names(householdsubset))
		
	
						##7 - selecting the rows 1st/2nd February 2007. row numbers 66637-69516
						
						##7.1 - changing date from factor to time
						householdsubset$date <- strptime(householdsubset$date, format = "%d/%m/%Y %H:%M:%S")	
						
						##7.2 - select the rows 1st/2nd February 2007
						datasubset <- subset(householdsubset, date >= "2007-02-01" & date <= "2007-02-02 23:59:00")
	
	
							##8 - generating the graph						

							#8.1 - creating a blank graph
							with(datasubset, plot(datasubset$date, datasubset$submetering1, xlab= "", ylab = "Energy sub metering (Watt Hour)", type = "n"))

							##8.2 - plotting the sub metering lines on the graph
							lines(datasubset$date, datasubset$submetering1, type = "l", lty = 1, lwd = 1, col = "black")
													
							lines(datasubset$date, datasubset$submetering2, type = "l", lty = 1, lwd = 1, col = "red")
													
							lines(datasubset$date, datasubset$submetering3, type = "l", lty = 1, lwd = 1, col = "blue")
													
							##8.3 - adding the legend to the graph
							legend("topright", bty = "o", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
							
														
								##9 - closing the graphic png file
								dev.off()
							