DATA SCIENCE SPECIALISM

MODULE 4 - Exploratory Data Analysis

PROJECT 1
==================================================================================

PLOT 4 DETAILS -

Graph style	:	four graphs - 

				top left - global active power (as plot 2)
				
				bottom left - energy sub metering (as plot 3 without line around legend)
				
				top right - voltage against datetime
				
				bottom right - global reactive power against datetime

Graph size	:	480 pixels by 480 pixels

Graph title :	none

Dataset		:	dates 2007-02-01 and 2007-02-02 (1st & 2nd of February 2007)

=================================================================================

R SCRIPT

##1 - saving the output graph (as a png) generated by the R script below - automatically saved as size 480 x 480 pixels
png("plot4.png")


	##2 - loading libraries
	library(data.table)

	
		##3 - reading the dataset into R
		household <- read.table("household_power_consumption.txt", header = TRUE, sep = c(";"), na.strings = "?")
	
	
			##4 - create two data tables - 1) date & time, 2) global active power
			householddatesubset <- household[c(1:2)]
			restsubset <- household[c(3:5,7:9)]
				
				##5 - creating a data frame with merged date and time columns
				
				##5.1 - merged date and time into one column
				mergedsubset <- paste(householddatesubset$Date, householddatesubset$Time, sep = " ")

				##5.2 - merge date/time df with power df
				householdsubset <- cbind(mergedsubset, restsubset)

				
					##6 - renaming the columns of the household dataset - tidy data set
					names(householdsubset) <- gsub("mergedsubset", "datetime", names(householdsubset))
					names(householdsubset) <- gsub("Global_active_power", "globalactivepower (Kilowatts)", names(householdsubset))	
					names(householdsubset) <- gsub("Global_reactive_power", "globalreactivepower (Kilowatts)", names(householdsubset))	
					names(householdsubset) <- gsub("Voltage", "voltage (Volts)", names(householdsubset))
					names(householdsubset) <- gsub("Sub_metering_1", "submetering1 (Watt Hour)", names(householdsubset))
					names(householdsubset) <- gsub("Sub_metering_2", "submetering2 (Watt Hour)", names(householdsubset))
					names(householdsubset) <- gsub("Sub_metering_3", "submetering3 (Watt Hour)", names(householdsubset))
					
	
						##7 - selecting the rows 1st/2nd February 2007. row numbers 66637-69516
						
						##7.1 - changing date from factor to time
						householdsubset$datetime <- strptime(householdsubset$datetime, format = "%d/%m/%Y %H:%M:%S")	
						
						##7.2 - select the rows 1st/2nd February 2007
						datasubset <- subset(householdsubset, datetime >= "2007-02-01" & datetime <= "2007-02-02 23:59:00")
	
	
							##8 - generating the graph						

							##8.1 - how to fill the graphic with the four graphs - 2 rows and 2 columns. Filling by columns.
							par(mfcol = c(2,2))
							
							##8.2 - selecting the data table a the basis of the graph
							with(datasubset, {

								##8.3 - graph top right
								plot(datasubset$datetime, datasubset$globalactivepower, xlab= "", ylab = "Global Active Power (Kilowatts)", type = "n")
									lines(datasubset$datetime, datasubset$globalactivepower, type = "l", lty = 1, lwd = 1)

								
								##8.4 - graph bottom right
								plot(datasubset$datetime, datasubset$submetering1, xlab= "", ylab = "Energy sub metering (Watt Hour)", type = "n")
									lines(datasubset$datetime, datasubset$submetering1, type = "l", lty = 1, lwd = 1, col = "black")
									lines(datasubset$datetime, datasubset$submetering2, type = "l", lty = 1, lwd = 1, col = "red")
									lines(datasubset$datetime, datasubset$submetering3, type = "l", lty = 1, lwd = 1, col = "blue")
									legend("topright", bty = "n", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
									
								##8.5 - graph top right
								plot(datasubset$datetime, datasubset$voltage, ylab = "Voltage (Volts)", xlab = "datetime", type = "n")
									lines(datasubset$datetime, datasubset$voltage, type = "l", lty = 1, lwd = 1)
								
								##8.6 - graph bottom right
								plot(datasubset$datetime, datasubset$globalreactivepower, xlab = "datetime", ylab = "Global_reactive_power (Kilowatts)", type = "n")
									lines(datasubset$datetime, datasubset$globalreactivepower, type = "h", lty = 1, lwd = 1)
								
							##closing graph generation
							})
							
														
									##9 - closing the graphic png file
									dev.off()
